"""empty message

Revision ID: 66b6c4091a28
Revises: 90abef98079d
Create Date: 2023-01-05 18:20:33.342341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66b6c4091a28'
down_revision = '90abef98079d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts_prescribed',
    sa.Column('contacts_rx_id', sa.Integer(), nullable=False),
    sa.Column('patients_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contacts_rx_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['patients_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('contacts_rx_id', 'patients_id')
    )
    op.create_table('glasses_prescribed',
    sa.Column('glasses_rx_id', sa.Integer(), nullable=False),
    sa.Column('patients_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['glasses_rx_id'], ['glasses.id'], ),
    sa.ForeignKeyConstraint(['patients_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('glasses_rx_id', 'patients_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('glasses_prescribed')
    op.drop_table('contacts_prescribed')
    # ### end Alembic commands ###
