"""empty message

Revision ID: 90abef98079d
Revises: b55a99eb69ae
Create Date: 2023-01-04 21:03:41.792674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90abef98079d'
down_revision = 'b55a99eb69ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exp_date', sa.DateTime(), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('lens_brand', sa.String(), nullable=False),
    sa.Column('prescription', sa.Integer(), nullable=False),
    sa.Column('pres_od', sa.String(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts')
    # ### end Alembic commands ###
