"""empty message

Revision ID: d051c26f0b81
Revises: 66b6c4091a28
Create Date: 2023-01-05 19:01:47.906944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd051c26f0b81'
down_revision = '66b6c4091a28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_column('patient_id')

    with op.batch_alter_table('glasses', schema=None) as batch_op:
        batch_op.drop_column('patient_id')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('current_srx')
        batch_op.drop_column('current_clrx')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_clrx', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('current_srx', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('glasses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
