"""empty message

Revision ID: 771c51c1f628
Revises: d051c26f0b81
Create Date: 2023-01-22 09:52:09.230005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '771c51c1f628'
down_revision = 'd051c26f0b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)

    # ### end Alembic commands ###
