"""empty message

Revision ID: b55a99eb69ae
Revises: 42f62840e251
Create Date: 2023-01-04 21:01:16.836433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b55a99eb69ae'
down_revision = '42f62840e251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glasses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exp_date', sa.DateTime(), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('prescription', sa.Integer(), nullable=False),
    sa.Column('pres_od', sa.String(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('glasses')
    # ### end Alembic commands ###
